export { default as AuthPage } from './auth'
export { default as DashboardPage } from './dashboard'
export { default as SettingsPage } from './settings'
export { default as AdminPage } from './admin'
export { default as StockPage } from './stock'